set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS true [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE Yes [current_design]
######################################################################

#50MHz single-ended clock
set_property -dict {PACKAGE_PIN D27 IOSTANDARD LVCMOS18} [get_ports gclk]
create_clock -period 20.000 [get_ports gclk]

#Reset wire active high
set_property -dict {PACKAGE_PIN B23 IOSTANDARD LVCMOS18 PULLTYPE PULLDOWN} [get_ports {ExtIO_J1_A60_rst}]


# PCI Express Interface
set_property PACKAGE_PIN V22 [get_ports pcie_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports pcie_rst_n]
# PCI Express reference clock 100MHz
create_clock -name pcie_ref_clk_p -period 10 [get_ports {pcie_ref_clk_p}]
set_property PACKAGE_PIN U8  [get_ports {pcie_ref_clk_p}]
# MGT locations
set_property PACKAGE_PIN M6  [get_ports {pcie_mgt_rxp[0]}]
set_property PACKAGE_PIN P6 [get_ports {pcie_mgt_rxp[1]}]
set_property PACKAGE_PIN R4  [get_ports {pcie_mgt_rxp[2]}]
set_property PACKAGE_PIN T6 [get_ports {pcie_mgt_rxp[3]}]
set_property PACKAGE_PIN V6  [get_ports {pcie_mgt_rxp[4]}]
set_property PACKAGE_PIN W4 [get_ports {pcie_mgt_rxp[5]}]
set_property PACKAGE_PIN Y6  [get_ports {pcie_mgt_rxp[6]}]
set_property PACKAGE_PIN AA4 [get_ports {pcie_mgt_rxp[7]}]
set_property PACKAGE_PIN L4  [get_ports {pcie_mgt_txp[0]}]
set_property PACKAGE_PIN M2  [get_ports {pcie_mgt_txp[1]}]
set_property PACKAGE_PIN N4  [get_ports {pcie_mgt_txp[2]}]
set_property PACKAGE_PIN P2  [get_ports {pcie_mgt_txp[3]}]
set_property PACKAGE_PIN T2  [get_ports {pcie_mgt_txp[4]}]
set_property PACKAGE_PIN U4  [get_ports {pcie_mgt_txp[5]}]
set_property PACKAGE_PIN V2  [get_ports {pcie_mgt_txp[6]}]
set_property PACKAGE_PIN Y2  [get_ports {pcie_mgt_txp[7]}]
#DCI
set_property slave_banks {32 34} [get_iobanks 33]



#On board LEDs
set_property -dict {PACKAGE_PIN R24 IOSTANDARD LVCMOS33} [get_ports LED_Green]
set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVCMOS33} [get_ports LED_Yellow]
set_property -dict {PACKAGE_PIN T21 IOSTANDARD LVCMOS33} [get_ports LED_Red]


#External I/O: J1
set_property -dict {PACKAGE_PIN F30 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[0]}]
set_property -dict {PACKAGE_PIN G30 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[1]}]
set_property -dict {PACKAGE_PIN D28 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[2]}]
set_property -dict {PACKAGE_PIN E28 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[3]}]
set_property -dict {PACKAGE_PIN F27 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[4]}]
set_property -dict {PACKAGE_PIN G28 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[5]}]
set_property -dict {PACKAGE_PIN D26 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[6]}]
set_property -dict {PACKAGE_PIN C26 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[7]}]
set_property -dict {PACKAGE_PIN H26 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[8]}]
set_property -dict {PACKAGE_PIN H27 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[9]}]
set_property -dict {PACKAGE_PIN G24 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[10]}]
set_property -dict {PACKAGE_PIN G25 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[11]}]
set_property -dict {PACKAGE_PIN G27 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[12]}]
set_property -dict {PACKAGE_PIN F26 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[13]}]
set_property -dict {PACKAGE_PIN E26 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[14]}]
set_property -dict {PACKAGE_PIN G19 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[15]}]
set_property -dict {PACKAGE_PIN J19 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[16]}]
set_property -dict {PACKAGE_PIN B20 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[17]}]
set_property -dict {PACKAGE_PIN C20 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[18]}]
set_property -dict {PACKAGE_PIN G23 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[19]}]
set_property -dict {PACKAGE_PIN D24 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[20]}]
set_property -dict {PACKAGE_PIN C24 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[21]}]
set_property -dict {PACKAGE_PIN B24 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[22]}]
set_property -dict {PACKAGE_PIN G29 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[23]}]
set_property -dict {PACKAGE_PIN F28 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[24]}]
set_property -dict {PACKAGE_PIN A28 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[25]}]
set_property -dict {PACKAGE_PIN B28 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[26]}]
set_property -dict {PACKAGE_PIN B25 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[27]}]
set_property -dict {PACKAGE_PIN C25 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[28]}]
set_property -dict {PACKAGE_PIN H30 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[29]}]
set_property -dict {PACKAGE_PIN B27 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[30]}]
set_property -dict {PACKAGE_PIN C29 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[31]}]
set_property -dict {PACKAGE_PIN B29 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[32]}]
set_property -dict {PACKAGE_PIN A27 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[33]}]
set_property -dict {PACKAGE_PIN H20 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[34]}]
set_property -dict {PACKAGE_PIN A23 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_A[35]}]

set_property -dict {PACKAGE_PIN G22 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[0]}]
set_property -dict {PACKAGE_PIN H22 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[1]}]
set_property -dict {PACKAGE_PIN F21 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[2]}]
set_property -dict {PACKAGE_PIN E21 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[3]}]
set_property -dict {PACKAGE_PIN L17 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[4]}]
set_property -dict {PACKAGE_PIN F22 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[5]}]
set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[6]}]
set_property -dict {PACKAGE_PIN K19 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[7]}]
set_property -dict {PACKAGE_PIN F20 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[8]}]
set_property -dict {PACKAGE_PIN E20 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[9]}]
set_property -dict {PACKAGE_PIN K20 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[10]}]
set_property -dict {PACKAGE_PIN H19 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[11]}]
set_property -dict {PACKAGE_PIN H21 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[12]}]
set_property -dict {PACKAGE_PIN C21 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[13]}]
set_property -dict {PACKAGE_PIN D21 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[14]}]
set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[15]}]
set_property -dict {PACKAGE_PIN A30 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[16]}]
set_property -dict {PACKAGE_PIN D22 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[17]}]
set_property -dict {PACKAGE_PIN B30 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[18]}]
set_property -dict {PACKAGE_PIN C30 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[19]}]
set_property -dict {PACKAGE_PIN C22 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[20]}]
set_property -dict {PACKAGE_PIN G20 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[21]}]
set_property -dict {PACKAGE_PIN D23 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[22]}]
set_property -dict {PACKAGE_PIN E23 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[23]}]
set_property -dict {PACKAGE_PIN D29 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[24]}]
set_property -dict {PACKAGE_PIN F23 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[25]}]
set_property -dict {PACKAGE_PIN E30 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[26]}]
set_property -dict {PACKAGE_PIN E29 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[27]}]
set_property -dict {PACKAGE_PIN A25 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[28]}]
set_property -dict {PACKAGE_PIN H25 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[29]}]
set_property -dict {PACKAGE_PIN E24 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[30]}]
set_property -dict {PACKAGE_PIN E25 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[31]}]
set_property -dict {PACKAGE_PIN H24 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[32]}]
set_property -dict {PACKAGE_PIN A26 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[33]}]
set_property -dict {PACKAGE_PIN F25 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J1_B[34]}]




#External I/O: J3
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[0]}]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[1]}]
set_property -dict {PACKAGE_PIN G14 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[2]}]
set_property -dict {PACKAGE_PIN H14 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[3]}]
set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[4]}]
set_property -dict {PACKAGE_PIN J16 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[5]}]
set_property -dict {PACKAGE_PIN G13 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[6]}]
set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[7]}]
set_property -dict {PACKAGE_PIN J13 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[8]}]
set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[9]}]
set_property -dict {PACKAGE_PIN J12 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[10]}]
set_property -dict {PACKAGE_PIN K14 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[11]}]
set_property -dict {PACKAGE_PIN J11 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[12]}]
set_property -dict {PACKAGE_PIN K11 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[13]}]
set_property -dict {PACKAGE_PIN L11 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[14]}]
set_property -dict {PACKAGE_PIN F11 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[15]}]
set_property -dict {PACKAGE_PIN H12 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[16]}]
set_property -dict {PACKAGE_PIN D11 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[17]}]
set_property -dict {PACKAGE_PIN E11 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[18]}]
set_property -dict {PACKAGE_PIN A16 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[19]}]
set_property -dict {PACKAGE_PIN A17 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[20]}]
set_property -dict {PACKAGE_PIN B18 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[21]}]
set_property -dict {PACKAGE_PIN A18 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[22]}]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[23]}]
set_property -dict {PACKAGE_PIN B19 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[24]}]
set_property -dict {PACKAGE_PIN A20 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[25]}]
set_property -dict {PACKAGE_PIN C19 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[26]}]
set_property -dict {PACKAGE_PIN D18 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[27]}]
set_property -dict {PACKAGE_PIN D17 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[28]}]
set_property -dict {PACKAGE_PIN A21 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[29]}]
set_property -dict {PACKAGE_PIN B22 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[30]}]
set_property -dict {PACKAGE_PIN E19 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[31]}]
set_property -dict {PACKAGE_PIN D19 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[32]}]
set_property -dict {PACKAGE_PIN A22 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[33]}]
set_property -dict {PACKAGE_PIN F17 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[34]}]
set_property -dict {PACKAGE_PIN F18 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[35]}]
set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_A[36]}]

set_property -dict {PACKAGE_PIN D14 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[0]}]
set_property -dict {PACKAGE_PIN E14 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[1]}]
set_property -dict {PACKAGE_PIN D12 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[2]}]
set_property -dict {PACKAGE_PIN D13 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[3]}]
set_property -dict {PACKAGE_PIN A13 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[4]}]
set_property -dict {PACKAGE_PIN B13 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[5]}]
set_property -dict {PACKAGE_PIN C14 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[6]}]
set_property -dict {PACKAGE_PIN B14 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[7]}]
set_property -dict {PACKAGE_PIN F12 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[8]}]
set_property -dict {PACKAGE_PIN E13 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[9]}]
set_property -dict {PACKAGE_PIN C15 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[10]}]
set_property -dict {PACKAGE_PIN B15 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[11]}]
set_property -dict {PACKAGE_PIN E15 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[12]}]
set_property -dict {PACKAGE_PIN A15 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[13]}]
set_property -dict {PACKAGE_PIN F16 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[14]}]
set_property -dict {PACKAGE_PIN L12 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[15]}]
set_property -dict {PACKAGE_PIN H11 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[16]}]
set_property -dict {PACKAGE_PIN L13 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[17]}]
set_property -dict {PACKAGE_PIN C11 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[18]}]
set_property -dict {PACKAGE_PIN A11 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[19]}]
set_property -dict {PACKAGE_PIN B12 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[20]}]
set_property -dict {PACKAGE_PIN G12 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[21]}]
set_property -dict {PACKAGE_PIN A12 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[22]}]
set_property -dict {PACKAGE_PIN K13 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[23]}]
set_property -dict {PACKAGE_PIN L15 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[24]}]
set_property -dict {PACKAGE_PIN K15 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[25]}]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[26]}]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[27]}]
set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[28]}]
set_property -dict {PACKAGE_PIN J17 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[29]}]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[30]}]
set_property -dict {PACKAGE_PIN C16 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[31]}]
set_property -dict {PACKAGE_PIN D16 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[32]}]
set_property -dict {PACKAGE_PIN B17 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[33]}]
set_property -dict {PACKAGE_PIN C17 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J3_B[34]}]



#External I/O: J4
set_property -dict {PACKAGE_PIN AB20 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[0]}]
set_property -dict {PACKAGE_PIN AA20 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[1]}]
set_property -dict {PACKAGE_PIN AF23 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[2]}]
set_property -dict {PACKAGE_PIN AE23 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[3]}]
set_property -dict {PACKAGE_PIN AC20 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[4]}]
set_property -dict {PACKAGE_PIN AC21 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[5]}]
set_property -dict {PACKAGE_PIN AD23 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[6]}]
set_property -dict {PACKAGE_PIN AE24 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[7]}]
set_property -dict {PACKAGE_PIN AC22 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[8]}]
set_property -dict {PACKAGE_PIN AD22 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[9]}]
set_property -dict {PACKAGE_PIN AD24 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[10]}]
set_property -dict {PACKAGE_PIN AA23 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[11]}]
set_property -dict {PACKAGE_PIN AB24 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[12]}]
set_property -dict {PACKAGE_PIN AC24 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[13]}]
set_property -dict {PACKAGE_PIN AC25 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[14]}]
set_property -dict {PACKAGE_PIN Y26 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[15]}]
set_property -dict {PACKAGE_PIN AA26 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[16]}]
set_property -dict {PACKAGE_PIN W27 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[17]}]
set_property -dict {PACKAGE_PIN Y25 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[18]}]
set_property -dict {PACKAGE_PIN AK21 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[19]}]
set_property -dict {PACKAGE_PIN AG20 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[20]}]
set_property -dict {PACKAGE_PIN AE20 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[21]}]
set_property -dict {PACKAGE_PIN AH20 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[22]}]
set_property -dict {PACKAGE_PIN AJ21 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[23]}]
set_property -dict {PACKAGE_PIN AH21 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[24]}]
set_property -dict {PACKAGE_PIN AG22 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[25]}]
set_property -dict {PACKAGE_PIN AH22 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[26]}]
set_property -dict {PACKAGE_PIN AG23 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[27]}]
set_property -dict {PACKAGE_PIN AF22 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[28]}]
set_property -dict {PACKAGE_PIN AJ22 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[29]}]
set_property -dict {PACKAGE_PIN AJ23 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[30]}]
set_property -dict {PACKAGE_PIN AJ24 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[31]}]
set_property -dict {PACKAGE_PIN AK25 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[32]}]
set_property -dict {PACKAGE_PIN AK20 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[33]}]
set_property -dict {PACKAGE_PIN Y28 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[34]}]
set_property -dict {PACKAGE_PIN W29 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[35]}]
set_property -dict {PACKAGE_PIN W28 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_A[36]}]

set_property -dict {PACKAGE_PIN AF27 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[0]}]
set_property -dict {PACKAGE_PIN AG27 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[1]}]
set_property -dict {PACKAGE_PIN AE28 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[2]}]
set_property -dict {PACKAGE_PIN AF28 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[3]}]
set_property -dict {PACKAGE_PIN AG28 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[4]}]
set_property -dict {PACKAGE_PIN AE26 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[5]}]
set_property -dict {PACKAGE_PIN AF26 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[6]}]
set_property -dict {PACKAGE_PIN AK28 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[7]}]
set_property -dict {PACKAGE_PIN AK29 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[8]}]
set_property -dict {PACKAGE_PIN AK30 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[9]}]
set_property -dict {PACKAGE_PIN AH27 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[10]}]
set_property -dict {PACKAGE_PIN AH26 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[11]}]
set_property -dict {PACKAGE_PIN AJ27 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[12]}]
set_property -dict {PACKAGE_PIN AJ26 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[13]}]
set_property -dict {PACKAGE_PIN AK26 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[14]}]
set_property -dict {PACKAGE_PIN AD26 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[15]}]
set_property -dict {PACKAGE_PIN AB23 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[16]}]
set_property -dict {PACKAGE_PIN AC26 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[17]}]
set_property -dict {PACKAGE_PIN AB22 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[18]}]
set_property -dict {PACKAGE_PIN AA22 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[19]}]
set_property -dict {PACKAGE_PIN AA28 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[20]}]
set_property -dict {PACKAGE_PIN AB29 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[21]}]
set_property -dict {PACKAGE_PIN AE25 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[22]}]
set_property -dict {PACKAGE_PIN AF25 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[23]}]
set_property -dict {PACKAGE_PIN AF20 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[24]}]
set_property -dict {PACKAGE_PIN AF21 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[25]}]
set_property -dict {PACKAGE_PIN AG25 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[26]}]
set_property -dict {PACKAGE_PIN AH25 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[27]}]
set_property -dict {PACKAGE_PIN AK24 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[28]}]
set_property -dict {PACKAGE_PIN AK23 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[29]}]
set_property -dict {PACKAGE_PIN AA21 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[30]}]
set_property -dict {PACKAGE_PIN Y20 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[31]}]
set_property -dict {PACKAGE_PIN Y21 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[32]}]
set_property -dict {PACKAGE_PIN Y24 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[33]}]
set_property -dict {PACKAGE_PIN Y23 IOSTANDARD LVCMOS18 PULLTYPE NONE} [get_ports {ExtIO_J4_B[34]}]












#ddr3 common
set_property -dict {PACKAGE_PIN AK11 IOSTANDARD SSTL15} [get_ports {ddr3_common_addr[0]}]
set_property -dict {PACKAGE_PIN AH11 IOSTANDARD SSTL15} [get_ports {ddr3_common_addr[1]}]
set_property -dict {PACKAGE_PIN AJ11 IOSTANDARD SSTL15} [get_ports {ddr3_common_addr[2]}]
set_property -dict {PACKAGE_PIN AD8 IOSTANDARD SSTL15} [get_ports {ddr3_common_addr[3]}]
set_property -dict {PACKAGE_PIN AD9 IOSTANDARD SSTL15} [get_ports {ddr3_common_addr[4]}]
set_property -dict {PACKAGE_PIN AG9 IOSTANDARD SSTL15} [get_ports {ddr3_common_addr[5]}]
set_property -dict {PACKAGE_PIN AE9 IOSTANDARD SSTL15} [get_ports {ddr3_common_addr[6]}]
set_property -dict {PACKAGE_PIN AH9 IOSTANDARD SSTL15} [get_ports {ddr3_common_addr[7]}]
set_property -dict {PACKAGE_PIN AE8 IOSTANDARD SSTL15} [get_ports {ddr3_common_addr[8]}]
set_property -dict {PACKAGE_PIN AH10 IOSTANDARD SSTL15} [get_ports {ddr3_common_addr[9]}]
set_property -dict {PACKAGE_PIN AB10 IOSTANDARD SSTL15} [get_ports {ddr3_common_addr[10]}]
set_property -dict {PACKAGE_PIN AK10 IOSTANDARD SSTL15} [get_ports {ddr3_common_addr[11]}]
set_property -dict {PACKAGE_PIN AG10 IOSTANDARD SSTL15} [get_ports {ddr3_common_addr[12]}]
set_property -dict {PACKAGE_PIN AJ9 IOSTANDARD SSTL15} [get_ports {ddr3_common_addr[13]}]
set_property -dict {PACKAGE_PIN AK9 IOSTANDARD SSTL15} [get_ports {ddr3_common_addr[14]}]

set_property -dict {PACKAGE_PIN AH14 IOSTANDARD SSTL15} [get_ports {ddr3_common_ba[0]}]
set_property -dict {PACKAGE_PIN AE11 IOSTANDARD SSTL15} [get_ports {ddr3_common_ba[1]}]
set_property -dict {PACKAGE_PIN AJ14 IOSTANDARD SSTL15} [get_ports {ddr3_common_ba[2]}]

set_property -dict {PACKAGE_PIN AC10 IOSTANDARD SSTL15} [get_ports {ddr3_common_cas_n}]
set_property -dict {PACKAGE_PIN AD11 IOSTANDARD DIFF_SSTL15} [get_ports {ddr3_common_ck_n}]
set_property -dict {PACKAGE_PIN AD12 IOSTANDARD DIFF_SSTL15} [get_ports {ddr3_common_ck_p}]
set_property DIFF_TERM TRUE [get_ports {ddr3_common_ck_p}]
set_property DIFF_TERM TRUE [get_ports {ddr3_common_ck_n}]
set_property -dict {PACKAGE_PIN AK13 IOSTANDARD SSTL15} [get_ports {ddr3_common_cke}]
set_property -dict {PACKAGE_PIN AF11 IOSTANDARD SSTL15} [get_ports {ddr3_common_cs_n}]
set_property -dict {PACKAGE_PIN AC12 IOSTANDARD SSTL15} [get_ports {ddr3_common_ras_n}]
set_property -dict {PACKAGE_PIN AJ3 IOSTANDARD LVCMOS15} [get_ports {ddr3_common_reset_n}]
set_property -dict {PACKAGE_PIN AC11 IOSTANDARD SSTL15} [get_ports {ddr3_common_we_n}]
set_property -dict {PACKAGE_PIN AK14 IOSTANDARD SSTL15} [get_ports {ddr3_common_odt}]

#ddr3 U1
set_property -dict {PACKAGE_PIN AF17 IOSTANDARD SSTL15} [get_ports {ddr3_U1_dm}]
set_property -dict {PACKAGE_PIN AH19 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U1_dq[0]}]
set_property -dict {PACKAGE_PIN AK19 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U1_dq[1]}]
set_property -dict {PACKAGE_PIN AG19 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U1_dq[2]}]
set_property -dict {PACKAGE_PIN AD19 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U1_dq[3]}]
set_property -dict {PACKAGE_PIN AG18 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U1_dq[4]}]
set_property -dict {PACKAGE_PIN AE19 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U1_dq[5]}]
set_property -dict {PACKAGE_PIN AF18 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U1_dq[6]}]
set_property -dict {PACKAGE_PIN AJ19 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U1_dq[7]}]
set_property -dict {PACKAGE_PIN AK18 IOSTANDARD DIFF_SSTL15_T_DCI} [get_ports {ddr3_U1_dqs_n}]
set_property -dict {PACKAGE_PIN AJ18 IOSTANDARD DIFF_SSTL15_T_DCI} [get_ports {ddr3_U1_dqs_p}]
set_property DIFF_TERM TRUE [get_ports {ddr3_U1_dqs_n}]
set_property DIFF_TERM TRUE [get_ports {ddr3_U1_dqs_p}]

#ddr3 U6
set_property -dict {PACKAGE_PIN Y15 IOSTANDARD SSTL15} [get_ports {ddr3_U6_dm}]
set_property -dict {PACKAGE_PIN AE15 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U6_dq[0]}]
set_property -dict {PACKAGE_PIN AB15 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U6_dq[1]}]
set_property -dict {PACKAGE_PIN AC14 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U6_dq[2]}]
set_property -dict {PACKAGE_PIN AA16 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U6_dq[3]}]
set_property -dict {PACKAGE_PIN AD14 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U6_dq[4]}]
set_property -dict {PACKAGE_PIN AA17 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U6_dq[5]}]
set_property -dict {PACKAGE_PIN AA15 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U6_dq[6]}]
set_property -dict {PACKAGE_PIN Y16 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U6_dq[7]}]
set_property -dict {PACKAGE_PIN AC15 IOSTANDARD DIFF_SSTL15_T_DCI} [get_ports {ddr3_U6_dqs_n}]
set_property -dict {PACKAGE_PIN AC16 IOSTANDARD DIFF_SSTL15_T_DCI} [get_ports {ddr3_U6_dqs_p}]
set_property DIFF_TERM TRUE [get_ports {ddr3_U6_dqs_n}]
set_property DIFF_TERM TRUE [get_ports {ddr3_U6_dqs_p}]

#ddr3 U14
set_property -dict {PACKAGE_PIN AC7 IOSTANDARD SSTL15} [get_ports {ddr3_U14_dm}]
set_property -dict {PACKAGE_PIN AD3 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U14_dq[0]}]
set_property -dict {PACKAGE_PIN AD4 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U14_dq[1]}]
set_property -dict {PACKAGE_PIN AC1 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U14_dq[2]}]
set_property -dict {PACKAGE_PIN AD6 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U14_dq[3]}]
set_property -dict {PACKAGE_PIN AC4 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U14_dq[4]}]
set_property -dict {PACKAGE_PIN AE6 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U14_dq[5]}]
set_property -dict {PACKAGE_PIN AC2 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U14_dq[6]}]
set_property -dict {PACKAGE_PIN AC5 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U14_dq[7]}]
set_property -dict {PACKAGE_PIN AD1 IOSTANDARD DIFF_SSTL15_T_DCI} [get_ports {ddr3_U14_dqs_n}]
set_property -dict {PACKAGE_PIN AD2 IOSTANDARD DIFF_SSTL15_T_DCI} [get_ports {ddr3_U14_dqs_p}]
set_property DIFF_TERM TRUE [get_ports {ddr3_U14_dqs_n}]
set_property DIFF_TERM TRUE [get_ports {ddr3_U14_dqs_p}]

#ddr3 U18
set_property -dict {PACKAGE_PIN AK3 IOSTANDARD SSTL15} [get_ports {ddr3_U18_dm}]
set_property -dict {PACKAGE_PIN AH2 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U18_dq[0]}]
set_property -dict {PACKAGE_PIN AJ1 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U18_dq[1]}]
set_property -dict {PACKAGE_PIN AH4 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U18_dq[2]}]
set_property -dict {PACKAGE_PIN AH5 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U18_dq[3]}]
set_property -dict {PACKAGE_PIN AK1 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U18_dq[4]}]
set_property -dict {PACKAGE_PIN AH6 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U18_dq[5]}]
set_property -dict {PACKAGE_PIN AJ2 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U18_dq[6]}]
set_property -dict {PACKAGE_PIN AJ4 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U18_dq[7]}]
set_property -dict {PACKAGE_PIN AH1 IOSTANDARD DIFF_SSTL15_T_DCI} [get_ports {ddr3_U18_dqs_n}]
set_property -dict {PACKAGE_PIN AG2 IOSTANDARD DIFF_SSTL15_T_DCI} [get_ports {ddr3_U18_dqs_p}]
set_property DIFF_TERM TRUE [get_ports {ddr3_U18_dqs_n}]
set_property DIFF_TERM TRUE [get_ports {ddr3_U18_dqs_p}]

#ddr3 U25
set_property -dict {PACKAGE_PIN AB17 IOSTANDARD SSTL15} [get_ports {ddr3_U25_dm}]
set_property -dict {PACKAGE_PIN AC19 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U25_dq[0]}]
set_property -dict {PACKAGE_PIN AD18 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U25_dq[1]}]
set_property -dict {PACKAGE_PIN AA18 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U25_dq[2]}]
set_property -dict {PACKAGE_PIN AD17 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U25_dq[3]}]
set_property -dict {PACKAGE_PIN AB19 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U25_dq[4]}]
set_property -dict {PACKAGE_PIN AE18 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U25_dq[5]}]
set_property -dict {PACKAGE_PIN AB18 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U25_dq[6]}]
set_property -dict {PACKAGE_PIN AD16 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U25_dq[7]}]
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD DIFF_SSTL15_T_DCI} [get_ports {ddr3_U25_dqs_n}]
set_property -dict {PACKAGE_PIN Y19 IOSTANDARD DIFF_SSTL15_T_DCI} [get_ports {ddr3_U25_dqs_p}]
set_property DIFF_TERM TRUE [get_ports {ddr3_U25_dqs_n}]
set_property DIFF_TERM TRUE [get_ports {ddr3_U25_dqs_p}]

#ddr3 U28
set_property -dict {PACKAGE_PIN AE16 IOSTANDARD SSTL15} [get_ports {ddr3_U28_dm}]
set_property -dict {PACKAGE_PIN AK16 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U28_dq[0]}]
set_property -dict {PACKAGE_PIN AG15 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U28_dq[1]}]
set_property -dict {PACKAGE_PIN AF15 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U28_dq[2]}]
set_property -dict {PACKAGE_PIN AG14 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U28_dq[3]}]
set_property -dict {PACKAGE_PIN AH17 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U28_dq[4]}]
set_property -dict {PACKAGE_PIN AH15 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U28_dq[5]}]
set_property -dict {PACKAGE_PIN AJ17 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U28_dq[6]}]
set_property -dict {PACKAGE_PIN AK15 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U28_dq[7]}]
set_property -dict {PACKAGE_PIN AJ16 IOSTANDARD DIFF_SSTL15_T_DCI} [get_ports {ddr3_U28_dqs_n}]
set_property -dict {PACKAGE_PIN AH16 IOSTANDARD DIFF_SSTL15_T_DCI} [get_ports {ddr3_U28_dqs_p}]
set_property DIFF_TERM TRUE [get_ports {ddr3_U28_dqs_n}]
set_property DIFF_TERM TRUE [get_ports {ddr3_U28_dqs_p}]

#ddr3 U31
set_property -dict {PACKAGE_PIN AK4 IOSTANDARD SSTL15} [get_ports {ddr3_U31_dm}]
set_property -dict {PACKAGE_PIN AK8 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U31_dq[0]}]
set_property -dict {PACKAGE_PIN AK5 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U31_dq[1]}]
set_property -dict {PACKAGE_PIN AJ8 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U31_dq[2]}]
set_property -dict {PACKAGE_PIN AF7 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U31_dq[3]}]
set_property -dict {PACKAGE_PIN AF8 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U31_dq[4]}]
set_property -dict {PACKAGE_PIN AJ6 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U31_dq[5]}]
set_property -dict {PACKAGE_PIN AG7 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U31_dq[6]}]
set_property -dict {PACKAGE_PIN AK6 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U31_dq[7]}]
set_property -dict {PACKAGE_PIN AJ7 IOSTANDARD DIFF_SSTL15_T_DCI} [get_ports {ddr3_U31_dqs_n}]
set_property -dict {PACKAGE_PIN AH7 IOSTANDARD DIFF_SSTL15_T_DCI} [get_ports {ddr3_U31_dqs_p}]
set_property DIFF_TERM TRUE [get_ports {ddr3_U31_dqs_n}]
set_property DIFF_TERM TRUE [get_ports {ddr3_U31_dqs_p}]

#ddr3 U34
set_property -dict {PACKAGE_PIN AF6 IOSTANDARD SSTL15} [get_ports {ddr3_U34_dm}]
set_property -dict {PACKAGE_PIN AF3 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U34_dq[0]}]
set_property -dict {PACKAGE_PIN AF1 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U34_dq[1]}]
set_property -dict {PACKAGE_PIN AE4 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U34_dq[2]}]
set_property -dict {PACKAGE_PIN AE1 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U34_dq[3]}]
set_property -dict {PACKAGE_PIN AE5 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U34_dq[4]}]
set_property -dict {PACKAGE_PIN AE3 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U34_dq[5]}]
set_property -dict {PACKAGE_PIN AF5 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U34_dq[6]}]
set_property -dict {PACKAGE_PIN AF2 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U34_dq[7]}]
set_property -dict {PACKAGE_PIN AG3 IOSTANDARD DIFF_SSTL15_T_DCI} [get_ports {ddr3_U34_dqs_n}]
set_property -dict {PACKAGE_PIN AG4 IOSTANDARD DIFF_SSTL15_T_DCI} [get_ports {ddr3_U34_dqs_p}]
set_property DIFF_TERM TRUE [get_ports {ddr3_U34_dqs_n}]
set_property DIFF_TERM TRUE [get_ports {ddr3_U34_dqs_p}]

#ddr3 U35
set_property -dict {PACKAGE_PIN AA13 IOSTANDARD SSTL15} [get_ports {ddr3_U35_dm}]
set_property -dict {PACKAGE_PIN AA10 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U35_dq[0]}]
set_property -dict {PACKAGE_PIN AA11 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U35_dq[1]}]
set_property -dict {PACKAGE_PIN AA12 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U35_dq[2]}]
set_property -dict {PACKAGE_PIN Y11 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U35_dq[3]}]
set_property -dict {PACKAGE_PIN AB8 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U35_dq[4]}]
set_property -dict {PACKAGE_PIN Y10 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U35_dq[5]}]
set_property -dict {PACKAGE_PIN AB12 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U35_dq[6]}]
set_property -dict {PACKAGE_PIN AA8 IOSTANDARD SSTL15_T_DCI} [get_ports {ddr3_U35_dq[7]}]
set_property -dict {PACKAGE_PIN AC9 IOSTANDARD DIFF_SSTL15_T_DCI} [get_ports {ddr3_U35_dqs_n}]
set_property -dict {PACKAGE_PIN AB9 IOSTANDARD DIFF_SSTL15_T_DCI} [get_ports {ddr3_U35_dqs_p}]
set_property DIFF_TERM TRUE [get_ports {ddr3_U35_dqs_n}]
set_property DIFF_TERM TRUE [get_ports {ddr3_U35_dqs_p}]